--- # Testing how variables work in the vars section of a playbook
- hosts: '{{ myhosts }}'
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: '{{ gather }}'
  vars:
   myhosts: centos
   gather: yes
   pkg: hping3
  tasks:
  - name: Install the indicated software
    yum:
      name: '{{ pkg }}'
      state: latest 